name: OakleyHorses.com
favicon: null
layout_spectrum: 0.5286
typography_spectrum: 0.53386
title: 'OakleyHorses - Trusted for expert guidance on show jumpers, dressage horses and eventers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020106'
    - '#f8fbfd'
    - '#c9381f'
    - '#99acc7'
    - '#4f5055'
  brandStrength: 0.35124572995118797
  lightness: 0.2698885058052838
  saturation: 0.6554204970598221
  rhythmicContrast: 0.39618211425840855
purpose: []
