name: OakleyHorses.com
favicon: null
layout_spectrum: 0.15202496759593487
typography_spectrum: 0.08473229967057705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.35124572995118797
  lightness: 0.2698885058052838
  saturation: 0.6554204970598221
  rhythmicContrast: 0.39618211425840855
purpose: []
